apiVersion: v1
kind: Service
metadata:
  name: my-java-project-service
spec:
  selector:
    app: my-java-project
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 32551
  type: NodePort
